zeus_arm:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  joint_1_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: joint_1
    pid: {p: 200.0, i: 0.0, d: 0.0}
  joint_2_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: joint_2
    pid: {p: 200.0, i: 0.0, d: 0.0}
  joint_3_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: joint_3
    pid: {p: 200.0, i: 0.0, d: 0.0}
  joint_4_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: joint_4
    pid: {p: 200.0, i: 0.0, d: 0.0}
  joint_5_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: joint_5
    pid: {p: 200.0, i: 0.0, d: 0.0}

